apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hubble
  namespace: kube-system
  labels:
    app.kubernetes.io/name: hubble-ui
  annotations:
    gethomepage.dev/app: hubble-ui
    gethomepage.dev/description: Hubble
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Homelab
    gethomepage.dev/icon: cilium.png
    gethomepage.dev/name: Hubble
    gethomepage.dev/statusStyle: dot
spec:
  hostnames:
    - hubble-dev.neokube.net
