apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ghost
resources:
  - deployment.yaml
  - externalsecret.yaml
  - httproute.yaml
  - namespace.yaml
  - pvc.yaml
  - service.yaml
