apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cloudflare
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cloudflare
  data:
    - secretKey: ACCOUNT_ID
      remoteRef:
        key: secrets/cloudflare
        property: ACCOUNT_ID
    - secretKey: TOKEN
      remoteRef:
        key: secrets/cloudflare
        property: TOKEN
