apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBClusterBackup
metadata:
  finalizers:
    - percona.com/delete-backup
  name: backup
  namespace: pxc
spec:
  pxcCluster: pxc-db
  storageName: backup-pxc-db
