apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghost
  namespace: pxc
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ghost
  data:
    - secretKey: password
      remoteRef:
        key: secrets/ghost
        property: password
