apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pxc-db
  namespace: pxc
spec:
  interval: 30m
  chart:
    spec:
      chart: pxc-db
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: percona
        namespace: pxc
      interval: 5m

  values:
    pxc:
      persistence:
        size: 1Gi

    users:
      - name: ghost
        dbs:
          - ghost
        hosts:
          - "%"
        grants:
          - ALL
        withGrantOption: true
        passwordSecretRef:
          name: ghost
          key: password
