apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: phpmyadmin
  labels:
    app.kubernetes.io/name: phpmyadmin
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: phpmyadmin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: phpmyadmin
    spec:
      enableServiceLinks: true
      dnsPolicy: ClusterFirst
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: PMA_HOST
              value: pxc-db-haproxy.pxc.svc.cluster.local
