apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.3.0
  - release.yaml
  - repository.yaml

configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
