apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: client-info-secret
  namespace: synology-csi
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: client-info-secret
    creationPolicy: Owner
  data:
    - secretKey: client-info.yml
      remoteRef:
        key: secrets/synology
        property: client-info.yml
