apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole
  namespace: external-dns
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: pihole
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: secrets/pihole
        property: piholekey
