apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-passwords
  namespace: monitoring
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: db-passwords
  data:
    - secretKey: GHOST_DB_PASSWORD
      remoteRef:
        key: secrets/ghost
        property: password
