apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/ghost/
patches:
  - path: pvc.yaml
    target:
      kind: PersistentVolumeClaim
  - path: httproute.yaml
    target:
      kind: HTTPRoute
